version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "altopedia"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: 
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/alt-activities
      - /alt-activities/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
