default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5
  timeout: 5000

# Version not specified here, but will be PostgreSQL 11 as of February 2020.
# Apart from UUIDs, the site doesn't use any Postgres-specific features, so it
# should run on any recent version without issue.
development:
  <<: *default
  encoding: utf-8
  username: postgres
  password: altopedia
  host: db
  database: alt-activities-development

test:
  <<: *default
  username: postgres
  password: altopedia
  host: db
  database: alt-activities-test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
